Update for CDAP Release 3.5.0
cdap-guides/cdap-etl-guide pull request #37
Opened 2016-08-23 22:42 UTC by awholegunch

2016-08-25 00:28 UTC, albertshau commented on DBTableToCDAPTable/README.rst
> +#. ``numSplits``: A string of the number of splits to generate (optional).
everything is a string. Do we need to explicitly say this?

2016-08-25 00:28 UTC, albertshau commented on DBTableToCDAPTable/config.json
> +            "numSplits": 1,
1 -> "1"

2016-08-25 00:30 UTC, albertshau commented
minor comments. otherwise lgtm for readmes. They might require other updates but we can do those in a separate PR.

2016-08-26 17:33 UTC, awholegunch commented on DBTableToCDAPTable/README.rst
> +#. ``numSplits``: A string of the number of splits to generate (optional).
I don't think we ever explicitly say that. JSON itself does not require strings, but do we in _all_ our JSON?

If so, somewhere we should say that.

2016-08-26 17:33 UTC, awholegunch commented on DBTableToCDAPTable/config.json
> +            "numSplits": 1,
Fixed.

2016-08-26 17:39 UTC, awholegunch commented on DBTableToCDAPTable/README.rst
> +#. ``numSplits``: A string of the number of splits to generate (optional).
Added as https://issues.cask.co/browse/CDAP-7180. Will remove from here to complete this PR.

2016-08-26 18:12 UTC, wolf31o2 commented on RealtimeTwitterToHBase/README.rst
> +Table. The ``cdap-etl-realtime`` system artifact can be used to create an Application that
Should this be `cdap-data-streams`?

2016-08-26 18:13 UTC, wolf31o2 commented
One comment, otherwise 👍 LGTM

2016-08-26 21:04 UTC, awholegunch commented
This PR is "on-hold" as there are a number of errors still in the READMEs, plus everything should be tested.

2016-10-06 22:26 UTC, albertshau requested changes
one small comment, otherwise lgtm

2016-10-06 22:26 UTC, albertshau commented on RealtimeTwitterToHBase/config.json
> +            "ConsumerSecret": "GetConsumerSecretFromTwitter"
missing a comma here. Guess that's why the ':' in the next line is highlighted in red?

2016-10-06 22:30 UTC, awholegunch commented on RealtimeTwitterToHBase/config.json
> +            "ConsumerSecret": "GetConsumerSecretFromTwitter"
Probably.

2016-10-06 22:31 UTC, awholegunch commented on RealtimeTwitterToHBase/config.json
> +            "ConsumerSecret": "GetConsumerSecretFromTwitter"
That fixed it.

2016-10-06 22:31 UTC, merged